### ISSUE TITLE
Why is the Telegram in the "risk" section?

### ISSUE THREAD

**Issue by OlegZv** [vshymanskyy/StandWithUkraine#104]
Regarding https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/CyberSafety.md
What inspired you to add Telegram to the list of Low risk apps?

**Comment by vshymanskyy** [comment]
Do you think the risk is high, or that Tg should be removed from the list?

**Comment by gytisrepecka** [comment]
Telegram is not end-to-end encrypted as content is available to it's servers running proprietary software.

Make sure to read [the history of Telegram covered by WIRED](https://www.wired.com/story/how-telegram-became-anti-facebook/) to know more about Durov and think long and hard before trusting him.

Instead better recommend [Signal](https://signal.org/docs/) or [Threema](https://threema.ch/en/open-source).

**Comment by szamanr** [comment]
so you're advocating for non-e2e-encrypted software like Slack and Teams, but against Telegram, supposedly because it's not e2e-encrypted? seems like double standard to me.

note that Telegram does offer E2E encryption, albeit not by default. it is as secure as whatsapp, which has sham E2E encryption - chats are encrypted, but automatic backups stored on the servers are not - that's why you can access you chat history when you get a new phone. secret chats on Telegram are as secure as signal.

https://www.wikiwand.com/en/Telegram_(software)#History

Pavel Durov left Russia and VK claiming the company had been taken over by the government. he started Telegram in Berlin and was later moved to Dubai. it does not pay taxes in Russia has no ties to Russia.

> In 2014, Pavel Durov fled the country after allies of the Kremlin took control of the social networking site most know just as VK. Russia's intelligence agency had asked Durov to turn over the data of anti-Kremlin protesters. Durov refused to do so.

([source](https://www.npr.org/2022/03/14/1086483703/telegram-ukraine-war-russia))

Telegram is a major source of independent news about Ukraine for Belarussian and Russian opposition (e.g. Nexta). 

> it is one of the few places Russians can access independent news about the war.

> "Russians are really disconnected from the reality of what happening to their country," Andrey said. "So Telegram has become essential for understanding what's going on to the Russian-speaking world."

([source](https://www.npr.org/2022/03/14/1086483703/telegram-ukraine-war-russia))

Russia has even blocked access to Telegram in the past for failing to provide users' data to the state: 
https://www.wikiwand.com/en/Blocking_of_Telegram_in_Russia
https://www.wilsoncenter.org/blog-post/russias-war-telegram-and-what-it-tells-us-about-russian-politics

please remove Telegram from the list of risky software.

**Comment by jdreesen** [comment]
In response to the false claims of security in #200 (which was locked minutes before I could respond):

> note that Telegram does offer E2E encryption, albeit not by default. 

But it does so only for one-to-one chats, **not** for groups & channels!

> it is as secure as whatsapp, which has sham E2E encryption - chats are encrypted, but automatic backups stored on the servers are not - that's why you can access you chat history when you get a new phone.

The difference is that WhatsApp's backups are not stored on WhatsApp's own servers, but in iCloud/Google Drive. So WhatsApp/Meta has no access to them. Moreover, **any** kind of chat on WhatsApp is encrypted. Therefore, I would definitely consider it more secure.

Also, WhatsApp supports encrypted backups (disabled by default).
See: https://faq.whatsapp.com/490592613091019?locale=en_US

> secret chats on Telegram are as secure as signal.

That's a bold claim, as Telegram uses a proprietary, custom-designed encryption protocol, which is never a good idea, while Signal's open protocol is considered the gold standard (and is also used by WhatsApp).

**Comment by szamanr** [comment]
@vshymanskyy 

> Please stop posting this manipulative bs:
>
> >    advocating for non-e2e-encrypted software like Slack and Teams, but against Telegram
>
> ...we're not advocating for Slack or Teams.

yes, you are. direct quote from the cyber safety page (https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/CyberSafety.md):

> Create an additional channel of communication with important contacts (i.e. Signal/Slack/Teams)

let's please not resort to insult such as "manipulative" or "bs". i have done my research, have you done yours? or are you just jumping on the "CEO is russian therefore product bad" bandwagon? it's not rational. please reconsider.
