### ISSUE TITLE
Adding Moscow Times

### ISSUE THREAD

**Issue by shayneoneill** [vshymanskyy/StandWithUkraine#124]
May I make a , possibly controversial, suggestion.

Moscow Times! 

Yes it is a Russian outlet, but they appear to take an anti-war and anti-putin stance in their editorial direction. My understanding is the editorial team have been forced to flee russia, although they retain some contributors in the country. I've found their site to be quite free of propaganda, and I think it might be an important voice for the following reason;-

The United states was in an unjust war against Vietnam starting in the 1950s and ending in the early 1970s. The US also lost this war , to a country that was bombed, battered, and decades behind the US in its capacities.

The reason for this was twofold. 
1) The Vietnamese put up a relentless fight to free their country. Deploying Guerilla tactics they demonstrated that a combatant fighting for the very existance of his own country can be almost unbreatable.
2) As the bodies came home and American people started seeing that the war was costing them so much, coupled with the media reporting that the Vietnamese where subject to war crimes and terrible violence,  the american public turned hostile on the government. 
Eventually the combination of a war that seemed to go forever at terrible cost to the US, and a public angry that the war was happening at all, lead to the US being repelled and leaving the country.

I think this could happen too with Ukraine, although one must pray that to get there the price is not as high as it was for Vietnam. But to achieve these two conditions one first needs that Ukraine keeps fighting (Which is happening) , and 2) Independent media in Russia able to show the public that their government is lying to them must be supported so the russian p.eople can see that Putin has lost his mind and is authorizing terrible violence in their name, and that Russia is paying a price measured in Russian bodies. Putin values power above all else, if the people turn on him, he loses that power, thus we must turn the russian people aginst him using the Truth.

 So to that end, I suggest adding "Moscow Times" to the independent press section. Its not perfect, but I think it would be very useful. 
 URL here: https://www.themoscowtimes.com/
 
 Critique welcome.

**Comment by webknjaz** [comment]
> Critique welcome.

Traditionally, any so-called "liberals" and "anti-putinists" etc. still promote ukrainophobic moods. They pretend to align their interests with "anti-war" but the problem is deep in the culture, it's been there for centuries.

Your belief is based on the propagandist assumption that the people don't support the government (which is not true, confirmed by the polls and hundreds of years of history — "ordinary" people are who commit all of the atrocities you see in the news, not the government officials) or this is happening unexpectedly for the very first time (also not true: check out the history). But if you look into the cultural and historic contexts, you'll see that it's been going on for years. Generation after generation is raised in a ukrainophobic environment, there's been ethnic cleansing, forceful relocation of people, language and culture prohibition and appropriation, and genocides (yes! in plural!). They are literally raised to have a liberator complex. Many generations will have to change for this to improve.

So no, I don't think it's a good idea to promote anything r*ssia-related over the next 100 years at least. Crushing the ruscist rapist forces isn't going to suddenly change the whole environment new generations grow up in. Also, I don't see how independent media can force the entire nation to unlearn the propaganda to the point of questioning lies about hundreds of years of history (school years is when most people consume and remember this information, they mostly don't renew it later in their lives).

**Comment by vshymanskyy** [comment]
@shayneoneill I reviewed a few articles from Moscow Times. While it looks good, it's hard to predict which messages may be hidden (and/or ideas promoted) by different authors in the Moscow Times.
I do appreciate their efforts, but I'm a bit puzzled. I'm not firmly against adding them to the list, so I'l ask the Ukrainian OSS community to comment on this. Please press :heart: to vote for adding or :disappointed: against adding it.

**Comment by denysdovhan** [comment]
My opinion: while we are still at war with Russia it’s not appropriate to promote any Russian media, including so-called liberals.

Any Russian or Belorussian media can potentially be biased. Add Polish, Georgian, Turkish, etc media as an unbiased sources.

**Comment by shayneoneill** [comment]
Whilst I think I prefer its inclusion, it should be up to the Ukranian OSS cats. Its their homes in danger, not mine.

**Comment by hellomedia** [comment]
> Any Russian or Belorussian media can potentially be biased. Suggest Polish, Georgian, Turkish, etc media as the unbiased sources instead.

People, unbiased media does not exist.

Every media, every people, every government is biased from its cultural worldview.

When we understand that and stop thinking we are the only ones who are unbiased and reasonable, maybe things can start getting a bit better.

**Comment by vshymanskyy** [comment]
@hellomedia maybe you should spend more (personal?) time digging into the topic.
It's not about bias. It's about deliberate propaganda, which may be undercover as well. I'm not running a fact-checking company, nor I'm willing to spend a lot of time to monitor russian-originating news sites.

**Comment by vshymanskyy** [comment]
So why do you think we should treat Moscow Times as a reliable source of news and opinions?

**Comment by shayneoneill** [comment]
I didnt say "reliable". I said that I think its worth supporting anti-war and anti-putin media in russia to make this war politically unviable for putin.

**Comment by webknjaz** [comment]
> I said that I think its worth supporting anti-war and anti-putin media in russia to make this war politically unviable for putin.

We don't really want to care what the r*ssians do inside their country. Some of them kinda expect to be liberated by somebody else, by us, for example. But why would we give a fuck if they don't. You may've noticed, we're nothing like them. There's no expansional imperialist idea behind the Ukrainian nation. We want to be left alone and interact with the civilized world only, not solve problems by invading into somebody else's swamps.

Also, it's well-known that even so-called “opposition” is no different from the mainstream ukrainophobes. The only difference is the name of the leader, and that's it. So supporting them would be like supporting the rest of the terrorists, but with a different “flavor” of hatred against Ukrainians.

And yes, maybe there's a fraction of a percent of the population that wants to make things right. That one perhaps deserves some support, but it's so statistically miserable that it doesn't really make sense to think about them now at all. Not until the victory, plus maybe several decades of observation.
