### ISSUE TITLE
How to disable this S#!T in composer

### ISSUE THREAD

**Issue by Cholowao** [vshymanskyy/StandWithUkraine#182]
Please guys, I know you want support, but give me my freedom to not support this propaganda, can anyone tell me how i can disable this shit when i run composer command.

**Comment by dennyishere** [comment]
There is nothing here that restricts your freedom. You’re free to not use the composer, right? Someone’s regularly updates list of software alternatives on habr and even more — i’ve seen a whole online-table with a collection of companies, services, apps, packages, etc that dared to offend some of our fellow citizens and one’s can cry about it in appropriate column (it’s disgusting!). Also you’re shouldn’t use “propaganda” in this case — “information”, “agitation”, “advertising”. All the info I’ve seen there was a facts written in neutral form and your dirty words is inappropriate here. You’re free to stay coward trying to live in a fictional world made up of somehow and this is true too. But in the real world this small reminders of crimes committed “in the name of our flag” should be taken as a gift because barbarians would be throwing bombs, not words.

Please, change the mark of this topic. Be a fool is not a crime and topicstarter didn’t say anything even close to be nazi.

**Comment by webknjaz** [comment]
> Please, change the mark of this topic. Be a fool is not a crime and topicstarter didn’t say anything even close to be nazi.

Respectfully, I disagree. The label is applied following duck typing principle. If one uses their freedom of speech to repeat the talking point of the terrorist propaganda, they match the pattern just like any passive bystanders do.

**Comment by Cholowao** [comment]
All I ask is how can I disable this. I just don't feel comfortable.  I am sure if someone put 

#StandWithNonLGBT you would lose your mind right??.

Same here, just put an option to disable.

Something being free does not mean we have to support all political views of who sponsor this package..


With all due respect 🙏

**Comment by Cholowao** [comment]
I saw an answer you can use Chinese mirror... it didn't a trick, tho it will just start to cache everything and take a whole day...

But guys why can't we just put --ignore-political-message 😕 

What if I am supporting oppressed Palestinians, do I have rights to do so... If you guys decide to put this package out of politics we would have not discussing this we would now fixing bugs and have peaceful coding.

**Comment by vshymanskyy** [comment]
The easiest way to disable it is to end the war against Ukraine.
The sooner the war ends -> the sooner banners get removed.
