### ISSUE TITLE
I prefer to support peace

### ISSUE THREAD

**Issue by mahop-net** [vshymanskyy/StandWithUkraine#203]
As the 14. Dalai Lama said: "When you kill someone, or assist someone in doing so, it is like chopping off your own hand."

End the war - do not send weapons - send diplomats!!!

**Comment by webknjaz** [comment]
Well, educate yourself, then. What you're calling for is more genocide.

**Comment by mahop-net** [comment]
Hello @webknjaz I think you did not unterstand me...

I want an end of the war, I want an end of all over 50 wars going on right now on earth. I want to stop all the genozids going on in Ukraine, China, Israel, Africa ... just to name a few of them. I want a end of all political imprisonements which are taking place  all over the world, even in Germany...

But waepons and more war are not the way to solve all this!!!

**Comment by webknjaz** [comment]
Is that why you're literally reading the terrorist propaganda designed to make excuses for mass murder?
I suppose you don't have experience with such situations so I strongly encourage you to use diplomacy next time an armed robber comes to your home and starts raping your kids, alright? Because that, don't pretend to be on the high horse, it's disgust and ruscist.

**Comment by MaxGraey** [comment]
> End the war - do not send weapons - send diplomats!!!

Ukraine has been trying to resolve the conflict diplomatically for at least nine years. During that time the OSCE (Budapest Memorandum), UN, Red Cross International, Amnesty International, the Pope and many other international organizations couldn't do a fucking thing! Moreover, they have shown themselves to be absolutely useless.

The only thing the aggressor understands, the only thing that restrains the aggressor from further aggressive actions, is the understanding that someone is stronger than him and can give a decent response.

Come on, tell Israel and Palestine that they just need to disarm themselves by holding hands and singing a song about peace in the World!

"We want to live. Our neighbors want to see us dead. That doesn't leave much room for compromise" 
(Golda Meir - Prime Minister of Israel from 1969 to 1974, born in Kyiv)

**Comment by DavertMik** [comment]
@mahop-net 

> When you kill someone, or **assist someone in doing so**, it is like chopping off your own hand

With this issue you assist russians killing Ukrainians

> End the war - do not send weapons - send diplomats!!!

Unlike Ukraine, Russia is not receiving weapons from West.
So If West stops sending weapons to Ukraine, this will cause more killing on our side.

Which had do you prefer to chop if you assist in killing Ukrainians?

**Comment by mahop-net** [comment]
I want to make it clear here: I am an opponent of Putin. Even before the Ukraine war, he was oppressing his own people.

And I also want to make it clear here. I support Ukraine, especially the many refugees who came here to my city. I have given a lot of money so that the Ukrainian families coming here get food, a roof over their heads and the children get a place in school...

And I don't want the West to do nothing and watch.

I think we should do everything to stop the war as soon as possible. Best today. And that the people in Ukraine can live in peace again.

But do you really think that more weapons and more war will stop the killing?

**Comment by mahop-net** [comment]
@webknjaz about: added the [typical-russian-nazi] 

You tell me a typical russian nazi??? You don't know anything about me??? Are you really from ukraine? Maybe I should think it over to help the next ukrain refuggees coming here - if ukrains call me a nazi...

**Comment by MaxGraey** [comment]
> But do you really think that more weapons and more war will stop the killing?

In 2014, the Ukrainian army practically did not exist. And no one threatened Russia. Russia then came and annexed Crimea, then Donbass and Luhansk through its proxy troops. On February 23, 2022, no one threatened Russia either, and Ukraine had no air defenses. And Europe thought Kyiv would fall in a few weeks. Did that stop Putin? No! The weakness only provoked him to start a war.

Or are you suggesting that you surrender despite the monstrous genocide that Russia has already committed in Ukraine, to make it even greater? You were called a nazi because you are no different from the Russia's Z-nazis at first glance. At least your goals and rhetoric are identical. Perhaps that's something to think about.

**Comment by mahop-net** [comment]
So, what is your plan?

**Comment by MaxGraey** [comment]
> So, what is your plan?

![FpvoSW_WcAUBbLV](https://user-images.githubusercontent.com/1301959/221325579-ce4f86f4-654e-459e-a5f5-e3196a9b51f8.jpg)

**Comment by mahop-net** [comment]
???

**Comment by webknjaz** [comment]
> You tell me a typical russian nazi??? You don't know anything about me???

This label marks a certain behavior. What is posted here sufficiently matches the term "ruscist". And the label is made to mark such occasions. It's nothing personal. r*ssians also make loud statements about their "good intentions" but actions speak for themselves. Like your calls that are specifically used by ruzzian propagandists. They are only targeted at making it easier for the terrorists to commit ethnic cleansing.

> Are you really from ukraine? 

I am from Ukraine, yes. But I live abroad. This attitude of disrespectfully lowercasing the country name is also what matches the label FYI.

> Maybe I should think it over to help the next ukrain refuggees coming here - if ukrains call me a nazi...

It's up to your consciousness, really. If you ask me, I'd say that preventing the terror would be far more effective. And yes, this means weapons, in particular. With the ruscists kicked out of Ukraine, there wouldn't be as many refugees so no need for you to worry about helping anyone.

By cutting off the weapon suppliy you'd increase the number of victims because the only goal of ruzzia is genocide. There's no other goal. It's been demonstrated a lot of times in the past decade and in the last ~400 years. If you still don't understand this, educate yourself.

> But OK. I if look into the eyes of the children I will help them anyway, even if others like you are calling me a nazi...

You may or may not help a few refugees (we don't know this, really). But let's assume that you do. And that's a good thing.

Still, your statements in this discussion are exactly opposite of supporting Ukraine in general, as explained above.

In order to have refugees to be helping them, those refugees should appear as a result of something. That something is mass murder by the ruscist terrorists. So in order to help refugees, you first accept that the murderous maniacs should be allowed to commit atrocities, right?

Do you see now where your logical fallacy is coming from? You calls contradict your announced intent here.

P.S. I suppose the label name might be confusing to people unfamiliar with modern ruscists. It's not exactly the same as the German ones from the past but there's a certain level of resemblance. I think Timothy Snyder wrote a good explanation in the NYT article or his blog, I don't remember exactly but it should be googleable by anyone interested in self-education.

**Comment by ink-splatters** [comment]
@webknjaz Ти, опудало, ти навіщо малюєш зірки в слові Russian? Ти не уявляєш свою країну, ви розвели тут шовіністський смітник, який ніяк не відрізняється від самої огидної пропаганди.
Наклей на мене ярлик, клоун ебаний, ти ганьбиш Україну, це майданчик доджна бути відомий ширше за свою помийну діяльність. НЕ пов'язану ніяк з боротьбою
із фашизмом.
ваше прикриття - закінчити фінансові потоки в Рашку - це нахабна брехня,
ваша реальна мета -
розвести гебельщину.

Дякую
Слава Україні 🇺🇦

**Comment by webknjaz** [comment]
Alright, since this is going nowhere, and the comment with @ink-splatters's attempt to insult me with a Google Translate based message (style and contextual mistakes were similar to the ruscist fakes from the past, imitating Ukrainian dialogues) was removed (likely by himself?), I don't see any reason to keep this circus on.
