### ISSUE TITLE
I'm sorry.

### ISSUE THREAD

**Issue by 3jq** [vshymanskyy/StandWithUkraine#212]
I am the author of the following issue: https://github.com/vshymanskyy/StandWithUkraine/issues/119

And I wanted to bring my apologies, as now, I understand how important it is to inform people about war.

Russia does a lot of war crimes everyday and kills innocent Ukrainian people. And the worst thing is that many people believe that it's not true.

I am so sorry, I hope you'll accept my apologies.

**Comment by webknjaz** [comment]
I think I speak for most of us, saying that it's not enough to just apologize. Actions speak louder than words and there's a long way for the public to stop denying the collective responsibility. That said, your personal apology is a small positive step to self-improvement and I can accept that you might be changing. I don't have any evidence supporting the opposite, nor am I enthusiastic about it, anyway.
Please, understand that we, Ukrainians, do not particularly care how you do things on your side of the border so long as you don't poison our lives. My personal experience with russians is predominantly horrible (you can find some of those online) so I try to avoid such interactions when possible, which also means not trying to out the "good ones". We have seen some statements and even small forms of support throughout the years from people not hiding their names, but the percentage of such cases compared to the rest is within the margin of error and is statistically insignificant.
So don't expect many people suddenly wanting to do anything with you just because you apologized for something bad you did. You seem to be moving towards the right path of redemption but, please, don't seek validation from the Ukrainians. For many, these interactions are truly painful, regardless of your further motives and behavior in the moment.
Sometimes, we see this tendency to shift to us the responsibility to "fix russia(ns)" or "educate" them. This is insensitive and not fair and best — we shouldn't be subjected to reliving things just because someone isn't willing to self-educate, nor do we have imperialist aspirations to fix what's not ours.
Good luck in your journey! I'm going to close this issue since there's no action items left, I think.

**Comment by ink-splatters** [comment]
@webknjaz so that I have came to "Sorry" thread. Having been kind of wit thru my life, I should have mined probably some dark

hilarious, but may be not. It's a closed issue, but I do hope you'll receive a notification.

The reason is: I'd like to say sorry as well, without any seeking for validation from you or others, as per mentioned above, as I understand and agree with your point.

--

My big mistake was to judge you by very small sample of your responses which seemed to be insufficient, and I should have made my sample appropriate, at least: large enough.

The comment above and this https://github.com/vshymanskyy/StandWithUkraine/issues/2#issuecomment-1057918149

are self-explanatory, I want to express my sincere compassion in regard to at least this "My own home town is burning. I did see Russian Army invading Ukraine with my naked eyes" - your words from the aforementioned thread, following the same rule - with no expectations of anything in return.

It's a tragedy in which I cannot present myself uninvolved, inherently, because of my origin. Hence I was speaking out, to make a difference, but I don't see any further speaking out to be adding any value: I could not keep up with minimal viable ethics, while doing this, being triggered and mostly adding the noise, regardless I initially was coming out of best intentions.

--

When I personally think of Ukraine and the disaster which has been happening non-stop at least since 24.02.22, but actually since 2014 (as a remark: I've been to non-annexed Crimea around 04.01.14 which I adored a lot; and later on -  was deeply shocked by known events. So, you at least won't need to witness my "где вы были все эти 8 лет" shit).

apart from deeds which results can be assessed or at least acknowledged, I came to having realised that most appropriate thing to do (towards Ukrainians) is, well - _silence_.

I especially mean war related topics, as practically I have absolutely nothing to present to you, which would be both meaningful and would not cause unneeded emotional dialogs.

I haven't tried to "save the world", as everyone else with Ru passport except for a handful people, I didn't contribute _enough_ to my country's situation for the disaster to be avoided, I'm not serving at ВСУ (opposite to just a few Russians selected unbelievably diligently to act as independent unit - AFAIK, no claims for root source of truth),  my help to refugees? 
Well we contributed with humanitarian stuff to be delivered to Polish border, but it's nothing vs what I read here people have been doing, in order to help refugees.

I'm not "accepted" by significantly larger amount of people than say as of beginning of 2022?

Well it's a pity, I have lost a few very meaningful contacts, solely because it was too painful for people to continue communication, because of my origin; well, and what, seriously, I can accommodate and live with that.

So the only hope on this moment I have is that my response won't cause unambiguously negative feelings of yours, versus some other ones. It has been very low of me, man.

🇺🇦

**Comment by 3jq** [comment]
> I think I speak for most of us, saying that it's not enough to just apologize. Actions speak louder than words and there's a long way for the public to stop denying the collective responsibility. That said, your personal apology is a small positive step to self-improvement and I can accept that you might be changing. I don't have any evidence supporting the opposite, nor am I enthusiastic about it, anyway.
> Please, understand that we, Ukrainians, do not particularly care how you do things on your side of the border so long as you don't poison our lives. My personal experience with russians is predominantly horrible (you can find some of those online) so I try to avoid such interactions when possible, which also means not trying to out the "good ones". We have seen some statements and even small forms of support throughout the years from people not hiding their names, but the percentage of such cases compared to the rest is within the margin of error and is statistically insignificant.
> So don't expect many people suddenly wanting to do anything with you just because you apologized for something bad you did. You seem to be moving towards the right path of redemption but, please, don't seek validation from the Ukrainians. For many, these interactions are truly painful, regardless of your further motives and behavior in the moment.
> Sometimes, we see this tendency to shift to us the responsibility to "fix russia(ns)" or "educate" them. This is insensitive and not fair and best — we shouldn't be subjected to reliving things just because someone isn't willing to self-educate, nor do we have imperialist aspirations to fix what's not ours.
> Good luck in your journey! I'm going to close this issue since there's no action items left, I think.

I get it, yes.
Just felt bad because of my comment, and decided to make this apology thread.

**Comment by jemartin-r7** [comment]
Glory to Russia. It will free.
