### ISSUE TITLE
does symfony no longer support Ukraine?

### ISSUE THREAD

**Issue by 55pingvin** [vshymanskyy/StandWithUkraine#262]
Why has Ukraine's support information disappeared from home page of the [symfony](https://symfony.com/)?

**Comment by webknjaz** [comment]
Ah, the story starts @ https://github.com/symfony-cli/symfony-cli/commit/7b1629faea560cc8b0c917872fae3ca62d13f250 and https://github.com/symfony-cli/symfony-cli/issues/304.

And of course the rhetoric is filled with "people dying is politics". This usually makes folks feel better about performing actions that are direct or indirect support of the terrorist groups like ruscists that cause said "dying". Nobody is brave enough to plainly say they are fine with ethnic cleansing. They always hide behind "politics" and similar nonsense.

**Comment by webknjaz** [comment]
@Nyholm since you made an abusive comment in the locked issue, I'll reply to you here.

First, may we ask you to refrain from using the word "political"? It's very triggering. You claim this to be about community but then proceed to saying things like this.
We have a long history of replacing any references to ethnic cleansing with a dismissive "this is politics". This is plain wrong. When you get robbed, do you expect people to say "this is politics and we must refrain from supporting you"? When your family is in mortal danger, is this just politics?
Standing by and being silent equates to supporting the oppressor. It's that simple. "Oh hey, wouldn't be discriminate against a terrorist? What if they have a really good reason for mass murder? Let them be. We don't support them, so ignoring them is fine". This type of behavior is what makes a community non-inclusive or even plain hostile.
Your stance may make sense if you drag it out of the context. But that lack of context is what makes it even more toxic.

So what we see now is inclusive towards anybody but Ukrainians. You can easily educate yourself. Instead, you shift the burden of feeling extremely unwelcome to others and it's not okay. Why do you expect people living in terror daily to feel welcome with such an attitude?

I guess my point is that "politics" is a widely known oppressive tool for dismissing anybody you want to exclude, not having to try understanding what's happening.

**Comment by Nyholm** [comment]
Hey. 

FYI, I was suggested to keep the thread locked until tomorrow morning. I dont want to kill the discussion, I just wanted to cool things down. 

> First, may we ask you to refrain from using the word "political"? 

I see that you are very correct. I did not know. But I think that is the issue. I am a decent programmer, I dont know how triggering that word really is. 

I know that I can only try to imagine the pain of Ukrainians right now. I dont know what I would do if I was in your situation. I am trying to talk with my Ukrainian friends regularly and offer them help. But there is a difference between what I do and think and what Symfony officially says and does. 

And I believe it would suck if a large community that I am part of just ignored that a foreign power invaded Sweden. 

If you were to decide, how would Symfony handle world conflicts like this? 
Btw, I am part of the Symfony.com/slack channel if you want to discuss more synchronously.

**Comment by Nyholm** [comment]
On your edit: 

> And.. "no clear side to support" WTF is this even?

Sorry, it might not have been clear. I was referring to the conflict in middle east.

**Comment by webknjaz** [comment]
@Nyholm I don't do PHP, just thought it's outraging that it's okay for such a community to _(passively)_ support the terrorists. I believe someone else from our small group of Ukrainian FOSS maintainers has already posted in other channels, I'll leave it to them to talk on slack — they'll convey the general perception just fine. Also, we have a lot of content here that document just how terrible ordinary ruscists behave as well as the reactions of the seemingly supportive communities where they operate — it's nice to be able to have a record of such conversations in public (slack is not very open/transparent in this regard).

Most of the days in our private chat people start early morning (or late/middle of the night) by comparing the notes of how their walls were shaking (more often than not — _in real time!_), or enumerating who's still alive, or how they were watching the drones maneuvering between the buildings, and sometimes hitting ones right in front of them. And, while I was lucky to be living in another country when the invasion became full-scale, it affected me personally too through relatives held at gunpoint, stripped off of the means of communication, robbed by the same ordinary ruscists that you're so eager to make feel welcome.

These are very real consequences of the culture you're trying to invite into your community. It's not just armed humans on the ground. These are also humans that promote acceptance of the culture of imperialism and terror. A part of their work is to convince people to remove signs of supporting Ukraine from the informational field.

The owner of this repository lost his house to a terrorist missile almost two years ago and now can't dedicate enough time to advance one of his popular projects: https://news.ycombinator.com/item?id=38681672. Another FOSS maintainer is getting death threats towards his daughters: https://twitter.com/mourner/status/1732047714798743903.

And giving in to such removals is explicit support of the terrorist state of r*ssia.

Another part of their work is using propagandist tools like whataboutism, term substitution to derail focus/attention from things that matter. The terrorist attacks of hamas is just one example. And it might deserve attention in a different *separate* context. But in the context where people talk about supporting Ukraine, its mentions appear to exclusively shift the focus to multiple unrelated things so that focused conversations don't survive.

These are small bits of propaganda that, when used on scale (and we see this on Twitter and GitHub, among other places), cause white noise, allowing to suppress the efforts to inform people about what's happening with whatever the ruscist propagandists planned for today.

This all is to say that whenever you add and remove support, this affects people IRL. Whenever you refuse to learn and declare yourself impartial, it affects people. Moreover — this usually works as support of the oppressor (and undermining the oppressed, subsequently).

The suggestion is simple ­— make an effort to educate yourself, and then, support people. Whenever you don't do this, you still support somebody, but likely not ones worth supporting.

One thing we observed over the past years was that some of use hoped (and assumed!) that software engineers in Muscovy must be smart and educated, and would see through the propaganda. But what we saw instead is that they are ordinary people and they keep propagating the rotten culture of colonialism and denying the existence of other cultures. They didn't have to learn to tolerate terrorism, it's just something that fits well into what they've been taught by previous generations.

Of course, there may be exceptions (and we've seen them), but they're so statistically insignificant that showing them off is rather harmful as it fools people that then get killed. This is one of the reasons we don't tolerate when somebody westsplains to us that there's "good r*ssians". Somebody may behave differently with you but not with us. This is very similar to when PoC or women tell others about their experiences with racism or rape, but you refuse to believe because your friend "couldn't have done such a terrible thing". If you want to be just, you'll have to listen to the stories of people who's going through things more carefully. Neutrality will only put you into the "antiukrainian" bucket in the people's eyes. "Don't pick sides" is a common manipulation we can expect from the bot networks on twitter, but then, you can use your own mind to decide.

You call yourself a decent programmers. "They" are also good programmers. They may contribute to your favorite project, and in an hour they'd use that project to help automate murdering Ukrainians. Having a technical background does not make one immune from being persuaded to support the modern-day Hitler.
You can educate yourself and that would be something to distinguish you from other decent programmers that may be very interested in writing good solutions for whatever the dictator says.
And of course, they're educated enough to say that you're excluding them whenever you mention Ukraine. Of course, they want to feel better about themselves, when they ask the community to help them where they're stuck trying to design another tool that would help kill more Ukrainians.
So is it enough to be technically aware to make social calls like removing support of Ukraine? I think not.

Not sure if it's helpful, but here's a good example of a person from the Python community I'm a part of, being understanding and supportive: https://github.com/nedbat/coveragepy/commit/5ec587caf0bd670a0af34ad5b766119689b91b56#commitcomment-73645112.

P.S. You may see other Ukrainians voicing displeasure with similar actions in other places on GitHub and wider internet. This is not because we enjoy talking about this with other people — there's a huge nation-wide trauma for decades. We just know how effectively the ruscists trick regular westerners into collaborating with Muscovy.

**Comment by Nyholm** [comment]
I appreciate you sharing and helping me to understand. I agree with you. You are not wrong at all.

**Comment by taa0662621456** [comment]
The easiest way is to first make something stupid, then write even more stupidity, and then make excuses and thank them for what they helped you understand.


Personally, I think your post about the rationale for ."symfony no longer supporting Ukraine" is complete idiocy, and I consider you an idiot. And your sweet, supposedly tactful behavior is just a mask for your Swedish assholeness. How many Ukrainian refugees did you specifically help and in what way? Just don’t say that we advised and provided information support. You are a coward!
